
package com.cdeledu.jxjywebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IJxjyWsService", targetNamespace = "http://jxjywebservice.cdeledu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IJxjyWsService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncUserInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SyncUserInfo")
    @ResponseWrapper(localName = "syncUserInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SyncUserInfoResponse")
    public String syncUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudyInfoForSDJLY", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetStudyInfoForSDJLY")
    @ResponseWrapper(localName = "getStudyInfoForSDJLYResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetStudyInfoForSDJLYResponse")
    public String getStudyInfoForSDJLY(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKnowledgePassMsgForChinajjr", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetKnowledgePassMsgForChinajjr")
    @ResponseWrapper(localName = "getKnowledgePassMsgForChinajjrResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetKnowledgePassMsgForChinajjrResponse")
    public String getKnowledgePassMsgForChinajjr(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJLYSDUserPassData", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetJLYSDUserPassData")
    @ResponseWrapper(localName = "getJLYSDUserPassDataResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetJLYSDUserPassDataResponse")
    public String getJLYSDUserPassData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQualifiedForCountyCounselor", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetQualifiedForCountyCounselor")
    @ResponseWrapper(localName = "getQualifiedForCountyCounselorResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetQualifiedForCountyCounselorResponse")
    public String getQualifiedForCountyCounselor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSignUpUserInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SyncSignUpUserInfo")
    @ResponseWrapper(localName = "syncSignUpUserInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SyncSignUpUserInfoResponse")
    public String syncSignUpUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncHbjlcyUserInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SyncHbjlcyUserInfo")
    @ResponseWrapper(localName = "syncHbjlcyUserInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SyncHbjlcyUserInfoResponse")
    public String syncHbjlcyUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCireaersMemberOpenCourseHour", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetCireaersMemberOpenCourseHour")
    @ResponseWrapper(localName = "getCireaersMemberOpenCourseHourResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetCireaersMemberOpenCourseHourResponse")
    public String getCireaersMemberOpenCourseHour(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "qgzxgcsSyncUserInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.QgzxgcsSyncUserInfo")
    @ResponseWrapper(localName = "qgzxgcsSyncUserInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.QgzxgcsSyncUserInfoResponse")
    public String qgzxgcsSyncUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudyMsgByIdCard", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetStudyMsgByIdCard")
    @ResponseWrapper(localName = "getStudyMsgByIdCardResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetStudyMsgByIdCardResponse")
    public String getStudyMsgByIdCard(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg15
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.UpdateUserInfo")
    @ResponseWrapper(localName = "updateUserInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.UpdateUserInfoResponse")
    public String updateUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        XMLGregorianCalendar arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        XMLGregorianCalendar arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        XMLGregorianCalendar arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendTrainPersonInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SendTrainPersonInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SendTrainPersonInfo")
    @ResponseWrapper(localName = "SendTrainPersonInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.SendTrainPersonInfoResponse")
    public String sendTrainPersonInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHbjlcyTrainResultInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetHbjlcyTrainResultInfo")
    @ResponseWrapper(localName = "getHbjlcyTrainResultInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetHbjlcyTrainResultInfoResponse")
    public String getHbjlcyTrainResultInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKnowledgePassMsgForCireaers", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetKnowledgePassMsgForCireaers")
    @ResponseWrapper(localName = "getKnowledgePassMsgForCireaersResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetKnowledgePassMsgForCireaersResponse")
    public String getKnowledgePassMsgForCireaers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudyInfoForJLY", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetStudyInfoForJLY")
    @ResponseWrapper(localName = "getStudyInfoForJLYResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.GetStudyInfoForJLYResponse")
    public String getStudyInfoForJLY(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReceiveTrainResultInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReceiveTrainResultInfo", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.ReceiveTrainResultInfo")
    @ResponseWrapper(localName = "ReceiveTrainResultInfoResponse", targetNamespace = "http://jxjywebservice.cdeledu.com/", className = "com.cdeledu.jxjywebservice.ReceiveTrainResultInfoResponse")
    public String receiveTrainResultInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
